packages:
  - "apps/*"
  - "packages/*"
catalog:
  typescript: 5.8.2
  prettier: ^3.6.0
  prettier-plugin-tailwindcss: ^0.6.11
  eslint: ^9.29.0
catalogs:
  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    "@types/react": ^19.1.0
    "@types/react-dom": ^19.1.1
onlyBuiltDependencies:
  - esbuild
